### ISSUE TITLE
Invalid registration attempt for an Ore Dictionary item with name wax has occurred. 

### ISSUE THREAD

**Issue by xenoflot** [AllTheLayers/ATLCraftCandlesMod#5]
I have the following in my server log. No crash so this is all the info I have for you!

Cheers

`[21:07:17] [Server thread/WARN] [FML/atlcraft]: ****************************************
[21:07:17] [Server thread/WARN] [FML/atlcraft]: * Invalid registration attempt for an Ore Dictionary item with name wax has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:595)
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:581)
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:579)
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at allthelayers.candles.main.ATLCraftOreDictionaryRegistry.getRegistry(ATLCraftOreDictionaryRegistry.java:10)
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at allthelayers.candles.main.ATLCraftMod.onPreInit(ATLCraftMod.java:135)
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[21:07:17] [Server thread/WARN] [FML/atlcraft]: ****************************************
[21:07:17] [Server thread/WARN] [FML/atlcraft]: ****************************************
[21:07:17] [Server thread/WARN] [FML/atlcraft]: * Invalid registration attempt for an Ore Dictionary item with name wax has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:595)
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:581)
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:579)
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at allthelayers.candles.main.ATLCraftOreDictionaryRegistry.getRegistry(ATLCraftOreDictionaryRegistry.java:11)
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at allthelayers.candles.main.ATLCraftMod.onPreInit(ATLCraftMod.java:135)
[21:07:17] [Server thread/WARN] [FML/atlcraft]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[21:07:17] [Server thread/WARN] [FML/atlcraft]: ****************************************
[21:07:19] [Server thread/TRACE] [atlcraft/atlcraft]: Sent event FMLPreInitializationEvent to mod atlcraft
[21:07:19] [Server thread/DEBUG] [FML/]: Bar Step: PreInitialization - ATLCraft Candles Mod took 1.841s`

**Comment by AllTheLayers** [comment]
I got this error while fixing another error. It is now fixed in MC1.12-Ver1.8
